// GENERATED by scripts/sync-video.mjs from backend/remotion/src - do not edit here.
import { track, type TrackKeyframe } from "../../engine/motion/keyframes";

/**
 * A camera as an operator thinks of it: where it looks, how far back it
 * is, from which angle, with which lens.
 *
 * `yaw` walks around the target (positive = camera moves to the target's
 * right), `pitch` looks down on it (positive = camera above). `distance`
 * is in world units. `fov` is the vertical field of view in degrees.
 * `panX`/`panY` truck the whole rig, `roll` tilts the horizon.
 */
export interface Camera3D {
  distance: number;
  yaw: number;
  pitch: number;
  fov: number;
  targetX: number;
  targetY: number;
  targetZ: number;
  panX: number;
  panY: number;
  roll: number;
}

export const CAMERA3D_REST: Camera3D = {
  distance: 4,
  yaw: 0,
  pitch: 0,
  fov: 32,
  targetX: 0,
  targetY: 0,
  targetZ: 0,
  panX: 0,
  panY: 0,
  roll: 0,
};

export type Camera3DKeyframe = TrackKeyframe<keyof Camera3D>;

export function camera3DAt(frame: number, keyframes: readonly Camera3DKeyframe[]): Camera3D {
  const at = (key: keyof Camera3D) => track(frame, keyframes, key, CAMERA3D_REST[key]);
  return {
    distance: at("distance"),
    yaw: at("yaw"),
    pitch: at("pitch"),
    fov: at("fov"),
    targetX: at("targetX"),
    targetY: at("targetY"),
    targetZ: at("targetZ"),
    panX: at("panX"),
    panY: at("panY"),
    roll: at("roll"),
  };
}

export function addCamera3D(a: Camera3D, b: Partial<Camera3D>): Camera3D {
  return {
    distance: a.distance * (b.distance ?? 1),
    yaw: a.yaw + (b.yaw ?? 0),
    pitch: a.pitch + (b.pitch ?? 0),
    fov: a.fov + (b.fov ?? 0),
    targetX: a.targetX + (b.targetX ?? 0),
    targetY: a.targetY + (b.targetY ?? 0),
    targetZ: a.targetZ + (b.targetZ ?? 0),
    panX: a.panX + (b.panX ?? 0),
    panY: a.panY + (b.panY ?? 0),
    roll: a.roll + (b.roll ?? 0),
  };
}

const DEG = Math.PI / 180;

/** Camera position and the point it looks at, in world units. */
export function resolveCamera(camera: Camera3D): {
  position: [number, number, number];
  target: [number, number, number];
} {
  const yaw = camera.yaw * DEG;
  const pitch = camera.pitch * DEG;
  const horizontal = camera.distance * Math.cos(pitch);
  const x = camera.targetX + camera.panX + horizontal * Math.sin(yaw);
  const y = camera.targetY + camera.panY + camera.distance * Math.sin(pitch);
  const z = camera.targetZ + horizontal * Math.cos(yaw);
  return {
    position: [x, y, z],
    target: [camera.targetX + camera.panX, camera.targetY + camera.panY, camera.targetZ],
  };
}
