// GENERATED by scripts/sync-video.mjs from backend/remotion/src - do not edit here.
import React from "react";
import { Composition } from "remotion";
import { ASPECT_DIMENSIONS, FPS, aspectKey, compositionId } from "./engine/aspect";
import { placeholderInput } from "./engine/placeholders";
import { TEMPLATES } from "./templates";
import { IPhoneReference, REFERENCE_DURATION } from "./scenes/iphone-reference";
import type { TemplateInput } from "./engine/types";

/**
 * One composition per template per aspect it declares. The gallery, the
 * editor and the renderer all address compositions by `compositionId`, so
 * adding a template to the list is the whole registration.
 */
export const RemotionRoot: React.FC = () => (
  <>
    {/* Reference scenes: motion tests with no content. Not in the library. */}
    {(["9:16", "16:9"] as const).map((aspect) => (
      <Composition
        key={`ref-iphone--${aspectKey(aspect)}`}
        id={`ref-iphone--${aspectKey(aspect)}`}
        component={IPhoneReference}
        durationInFrames={REFERENCE_DURATION}
        fps={FPS}
        width={ASPECT_DIMENSIONS[aspect].width}
        height={ASPECT_DIMENSIONS[aspect].height}
      />
    ))}
    {TEMPLATES.flatMap((template) =>
      template.aspects.map((aspect) => {
        const size = ASPECT_DIMENSIONS[aspect];
        return (
          <Composition
            key={compositionId(template.id, aspect)}
            id={compositionId(template.id, aspect)}
            component={template.component}
            durationInFrames={template.durationInFrames}
            fps={FPS}
            width={size.width}
            height={size.height}
            defaultProps={placeholderInput(template)}
            calculateMetadata={({ props }: { props: TemplateInput }) => ({
              durationInFrames:
                template.slots.duration && props.durationInFrames
                  ? Math.max(FPS, Math.round(props.durationInFrames))
                  : template.durationInFrames,
            })}
          />
        );
      }),
    )}
  </>
);
