// GENERATED by scripts/sync-video.mjs from backend/remotion/src - do not edit here.
import React, { useMemo } from "react";
import { ThreeCanvas } from "@remotion/three";
import { useRemotionEnvironment, useVideoConfig } from "remotion";
import { ACESFilmicToneMapping, PCFSoftShadowMap, SRGBColorSpace } from "three";
import { PREVIEW_QUALITY, QualityContext, RENDER_QUALITY } from "./quality";

/**
 * The WebGL canvas, sized to the composition and synchronised with the
 * Remotion frame. Rendering quality follows the environment: the Player
 * gets the light settings, the server render the heavy ones.
 *
 * Colour management is set once here: ACES tone mapping and an sRGB
 * output, the same pipeline a product shot would go through in a DCC.
 */
export const Scene3D: React.FC<{
  children: React.ReactNode;
  /** Scene background colour. Templates usually draw their own backdrop. */
  background?: string;
  style?: React.CSSProperties;
}> = ({ children, background = "#000000", style }) => {
  const { width, height } = useVideoConfig();
  const { isRendering } = useRemotionEnvironment();
  const quality = isRendering ? RENDER_QUALITY : PREVIEW_QUALITY;
  const gl = useMemo(
    () => ({
      antialias: quality.antialias,
      alpha: false,
      powerPreference: "high-performance" as const,
      // Remotion screenshots the page; the buffer must still be there.
      preserveDrawingBuffer: true,
    }),
    [quality.antialias],
  );

  return (
    <QualityContext.Provider value={quality}>
      <ThreeCanvas
        width={width}
        height={height}
        style={{ position: "absolute", inset: 0, ...style }}
        dpr={quality.dpr}
        gl={gl}
        shadows={{ type: PCFSoftShadowMap }}
        onCreated={({ gl: renderer, scene }) => {
          renderer.toneMapping = ACESFilmicToneMapping;
          renderer.toneMappingExposure = 1;
          renderer.outputColorSpace = SRGBColorSpace;
          renderer.setClearColor(background, 1);
          scene.background = null;
        }}
      >
        {children}
      </ThreeCanvas>
    </QualityContext.Provider>
  );
};
