// GENERATED by scripts/sync-video.mjs from backend/remotion/src - do not edit here.
import React from "react";
import { AbsoluteFill, useCurrentFrame, useVideoConfig } from "remotion";
import { Environment } from "../../engine/scene/Environment";
import { Stage, Placed } from "../../engine/scene/Stage";
import { ContactShadow, ScreenSpill, Surface } from "../../engine/scene/Floor";
import { MacBook, LID_OPEN, macbookGeometry } from "../../engine/devices/MacBook";
import { IPhone, iphoneGeometry } from "../../engine/devices/IPhone";
import { ScreenSequence } from "../../engine/content/ScreenSequence";
import { EndCard } from "../../engine/content/EndCard";
import { addCamera, cameraAt } from "../../engine/motion/camera";
import { kf } from "../../engine/motion/keyframes";
import { drift, DRIFT_PERIODS, ease, progress } from "../../engine/motion/easing";
import { layoutFor } from "../../engine/layout";
import { rgba } from "../../engine/palette";
import { CopyBand, Signature, splitBySurface } from "../_shared";
import type { TemplateDefinition, TemplateInput } from "../../engine/types";

const T = { lidEnd: 70, phoneEnd: 96, headline: 86, driftEnd: 236, copyLeave: 238, endCard: 256 };

/**
 * Laptop behind, phone in front and to the side, leaning in. The lid
 * finishes opening as the phone rises to meet it; then the camera drifts
 * across both while each plays its own screens - wide captures on the
 * laptop, tall ones on the phone.
 */
const Component: React.FC<TemplateInput> = ({ screens, logo, brand, copy, cta }) => {
  const frame = useCurrentFrame();
  const { width, height, fps } = useVideoConfig();
  const L = layoutFor(width, height);
  const t = frame / fps;
  const wide = L.aspect === "16:9";
  const { mobile, desktop } = splitBySurface(screens);

  const laptopWidth = Math.min(L.device.width * (wide ? 0.66 : 0.7), L.device.height * (wide ? 0.96 : 0.86));
  const g = macbookGeometry(laptopWidth);
  const phoneWidth = laptopWidth * 0.2;
  const p = iphoneGeometry(phoneWidth);
  const hingeX = L.device.x + L.device.width * (wide ? 0.46 : 0.44) - width / 2;
  const hingeY = L.device.y + L.device.height * (wide ? 0.7 : 0.7) - height / 2;

  const lidAngle = kf(frame, [{ at: 0, value: -48 }, { at: T.lidEnd, value: LID_OPEN + 2, easing: ease.cinematicInOut }, { at: T.lidEnd + 20, value: LID_OPEN, easing: ease.settle }]);
  const laptopBright = kf(frame, [{ at: 20, value: 0 }, { at: T.lidEnd - 8, value: 1, easing: ease.cinematicOut }]);
  const phoneRise = kf(frame, [{ at: 24, value: p.height * 1.4 }, { at: T.phoneEnd, value: 0, easing: ease.settle }]);
  const phoneBright = kf(frame, [{ at: 50, value: 0 }, { at: T.phoneEnd, value: 1, easing: ease.cinematicOut }]);
  const phoneYaw = kf(frame, [{ at: 24, value: -40 }, { at: T.phoneEnd, value: -20, easing: ease.cinematicOut }]);

  const move = cameraAt(frame, [
    { at: 0, dolly: 0.9, orbitX: 16, orbitY: -18 },
    { at: T.lidEnd + 10, dolly: 1, orbitX: 12, orbitY: -10, easing: ease.cinematicOut },
    { at: T.driftEnd, dolly: 1.12, orbitX: 8, orbitY: 6, easing: ease.smooth },
    { at: T.endCard + 20, dolly: 1.0, orbitY: -2, easing: ease.smooth },
  ]);
  const camera = addCamera(move, { orbitY: drift(t, DRIFT_PERIODS.slow, 0.4), y: drift(t, DRIFT_PERIODS.fast, L.unit * 0.002, 1) });

  const exposure = ease.cinematicOut(progress(frame, 0, 22));
  const endDim = ease.cinematicIn(progress(frame, T.endCard, T.endCard + 20));

  return (
    <AbsoluteFill style={{ backgroundColor: "#000" }}>
      <Environment primary={brand.primary} accent={brand.accent} exposure={exposure * (1 - endDim * 0.6)} keyLight={{ x: 0.3, y: 0.15 }} dust />
      <Stage camera={camera} origin={{ x: 0.5, y: 0.45 }}>
        <Placed x={hingeX} y={hingeY} width={0} height={0}>
          <Surface y={g.deckThickness + 3} size={L.unit * 14} color={brand.primary} focus={0.48} opacity={exposure} />
          <ContactShadow width={g.width} depth={g.deckDepth} y={g.deckThickness + 2} z={g.deckDepth / 2} strength={0.8} softness={30} />
          <ScreenSpill width={g.width} depth={g.deckDepth} y={g.deckThickness + 2} z={g.deckDepth * 0.9} color={rgba(brand.accent, 0.5)} intensity={laptopBright * 0.6} />
          <MacBook
            width={laptopWidth}
            lidAngle={lidAngle}
            brightness={laptopBright}
            accent={brand.accent}
            screen={(dims) => (
              <ScreenSequence screens={desktop} width={dims.width} height={dims.height} from={T.lidEnd - 20} to={T.endCard + 10} hold={Math.round(fps * 2.4)} transition="parallax" transitionFrames={14} scrollAmount={0.8} driftZoom={1.02} dim={endDim * 0.7} />
            )}
          />
          {/* The phone, in front of the deck's front edge, leaning on nothing. */}
          <Placed x={g.width * 0.42} y={-p.height * 0.42 + phoneRise} z={g.deckDepth * 1.05} width={0} height={0}>
            <ContactShadow width={p.width * 1.4} depth={p.width * 0.9} y={p.height * 0.5 + 6} strength={0.7 * phoneBright} softness={22} />
            <IPhone
              width={phoneWidth}
              brightness={phoneBright}
              sheenAngle={112 + phoneYaw}
              transform={`rotateY(${phoneYaw}deg) rotateX(-4deg)`}
              screen={(dims) => (
                <ScreenSequence screens={mobile} width={dims.width} height={dims.height} from={T.phoneEnd - 16} to={T.endCard + 10} hold={Math.round(fps * 1.7)} transition="slide-up" transitionFrames={12} scrollAmount={0.5} dim={endDim * 0.7} />
              )}
            />
          </Placed>
        </Placed>
      </Stage>
      <CopyBand layout={L} copy={copy} brand={brand} from={T.headline} leave={T.copyLeave} />
      <Signature layout={L} logo={logo} from={30} leave={T.endCard} />
      <EndCard from={T.endCard} cta={cta} brand={brand} logo={logo} badges="app" />
    </AbsoluteFill>
  );
};

export const template: TemplateDefinition = {
  id: "duo",
  name: "iPhone + MacBook",
  tagline: "Laptop behind, phone in front leaning in; wide captures on one, tall ones on the other.",
  category: "duo",
  devices: ["macbook", "iphone"],
  durationInFrames: 300,
  aspects: ["16:9", "1:1", "9:16"],
  slots: { screens: { min: 2, max: 8, surface: "any" }, logo: "optional", headline: true, subline: true, cta: true, accent: true, duration: null },
  component: Component,
};
