// GENERATED by scripts/sync-video.mjs from backend/remotion/src - do not edit here.
import React from "react";
import { AbsoluteFill, useCurrentFrame, useVideoConfig } from "remotion";
import { Environment } from "../../engine/scene/Environment";
import { Stage, Placed } from "../../engine/scene/Stage";
import { ContactShadow, ScreenSpill, Surface } from "../../engine/scene/Floor";
import { BoxAt } from "../../engine/scene/Overlay";
import { MacBook, LID_OPEN, macbookGeometry } from "../../engine/devices/MacBook";
import { IPhone } from "../../engine/devices/IPhone";
import { ScreenSequence } from "../../engine/content/ScreenSequence";
import { Logo } from "../../engine/content/Logo";
import { EndCard } from "../../engine/content/EndCard";
import { addCamera, cameraAt } from "../../engine/motion/camera";
import { kf } from "../../engine/motion/keyframes";
import { drift, DRIFT_PERIODS, ease, progress } from "../../engine/motion/easing";
import { layoutFor } from "../../engine/layout";
import { rgba } from "../../engine/palette";
import { CopyBand } from "../_shared";
import type { ImageAsset, TemplateDefinition, TemplateInput } from "../../engine/types";

const T = { revealEnd: 62, sweep: 40, moveStart: 84, moveEnd: 120, deviceIn: 96, headline: 130, copyLeave: 238, endCard: 254 };

/**
 * The mark first. It blooms out of the dark with a light sweep across
 * it, holds, then shrinks to the corner as the device scales up from
 * behind it and takes over. Phone or laptop, decided by the screens.
 * Ends on the mark again, large, with the store badges.
 */
const Component: React.FC<TemplateInput> = ({ screens, logo, brand, copy, cta }) => {
  const frame = useCurrentFrame();
  const { width, height, fps } = useVideoConfig();
  const L = layoutFor(width, height);
  const t = frame / fps;
  const wide = L.aspect === "16:9";
  const first = screens[0] as ImageAsset | undefined;
  const usePhone = !first || first.height >= first.width;

  // Logo: centre stage, then to the signature slot.
  const reveal = ease.cinematicOut(progress(frame, 6, T.revealEnd));
  const travel = ease.cinematicInOut(progress(frame, T.moveStart, T.moveEnd));
  const bigW = L.unit * 0.42;
  const bigH = L.unit * 0.24;
  const cx = width / 2 - bigW / 2;
  const cy = height * (wide ? 0.5 : 0.44) - bigH / 2;
  const sx = L.signature.x + (L.align === "left" ? 0 : (L.signature.width - bigW * 0.4) / 2);
  const sy = L.signature.y;
  const logoScale = 1 - travel * 0.6;
  const logoX = cx + (sx - cx) * travel;
  const logoY = cy + (sy - cy) * travel;
  const sweep = progress(frame, T.sweep, T.sweep + 30);

  // Device: scales up from behind the mark.
  const deviceIn = ease.settle(progress(frame, T.deviceIn, T.deviceIn + 40));
  const brightness = kf(frame, [{ at: T.deviceIn + 10, value: 0 }, { at: T.deviceIn + 40, value: 1, easing: ease.cinematicOut }]);

  const move = cameraAt(frame, [
    { at: 0, dolly: 1, orbitX: 0 },
    { at: T.deviceIn, dolly: 1 },
    { at: T.copyLeave, dolly: 1.1, orbitX: usePhone ? 2 : 9, orbitY: usePhone ? -6 : -8, easing: ease.smooth },
    { at: T.endCard + 20, dolly: 1.0, easing: ease.smooth },
  ]);
  const camera = addCamera(move, { orbitY: drift(t, DRIFT_PERIODS.slow, 0.5) * deviceIn, y: drift(t, DRIFT_PERIODS.fast, L.unit * 0.002, 2) * deviceIn });

  const exposure = ease.cinematicOut(progress(frame, 0, 30)) * (0.55 + 0.45 * deviceIn);
  const endDim = ease.cinematicIn(progress(frame, T.endCard, T.endCard + 20));

  const laptopWidth = Math.min(L.device.width * (wide ? 0.72 : 0.74), L.device.height * (wide ? 1.02 : 0.9));
  const g = macbookGeometry(laptopWidth);
  const phoneWidth = Math.min(L.device.height * (wide ? 0.42 : 0.36), L.device.width * (wide ? 0.4 : 0.46));
  const centreX = L.device.x + L.device.width / 2 - width / 2;
  const hingeY = L.device.y + L.device.height * (wide ? 0.72 : L.aspect === "1:1" ? 0.74 : 0.64) - height / 2;
  const phoneY = L.device.y + L.device.height / 2 - height / 2;

  return (
    <AbsoluteFill style={{ backgroundColor: "#000" }}>
      <Environment primary={brand.primary} accent={brand.accent} exposure={exposure * (1 - endDim * 0.6)} keyLight={{ x: 0.5, y: 0.35 }} dust />
      <Stage camera={camera} origin={{ x: 0.5, y: 0.45 }}>
        {usePhone ? (
          <Placed x={centreX} y={phoneY} width={0} height={0} scale={0.6 + 0.4 * deviceIn} style={{ opacity: deviceIn }}>
            <IPhone
              width={phoneWidth}
              brightness={brightness}
              transform={`rotateY(${-14 + drift(t, DRIFT_PERIODS.medium, 5, 1) * deviceIn}deg) rotateX(${drift(t, DRIFT_PERIODS.slow, 3, 4) * deviceIn}deg)`}
              screen={(dims) => (
                <ScreenSequence screens={screens} width={dims.width} height={dims.height} from={T.deviceIn + 10} to={T.endCard + 10} hold={Math.round(fps * 1.9)} transition="slide-up" transitionFrames={12} scrollAmount={0.6} dim={endDim * 0.7} />
              )}
            />
          </Placed>
        ) : (
          <Placed x={centreX} y={hingeY} width={0} height={0} scale={0.6 + 0.4 * deviceIn} style={{ opacity: deviceIn }}>
            <Surface y={g.deckThickness + 3} size={L.unit * 14} color={brand.primary} focus={0.48} opacity={deviceIn} />
            <ContactShadow width={g.width} depth={g.deckDepth} y={g.deckThickness + 2} z={g.deckDepth / 2} strength={0.8} softness={30} />
            <ScreenSpill width={g.width} depth={g.deckDepth} y={g.deckThickness + 2} z={g.deckDepth * 0.9} color={rgba(brand.accent, 0.5)} intensity={brightness * 0.7} />
            <MacBook
              width={laptopWidth}
              lidAngle={LID_OPEN}
              brightness={brightness}
              accent={brand.accent}
              screen={(dims) => (
                <ScreenSequence screens={screens} width={dims.width} height={dims.height} from={T.deviceIn + 10} to={T.endCard + 10} hold={Math.round(fps * 2.2)} transition="parallax" transitionFrames={14} scrollAmount={0.8} dim={endDim * 0.7} />
              )}
            />
          </Placed>
        )}
      </Stage>

      {/* The mark, in screen space so it can cross from centre to corner. */}
      {logo ? (
        <div
          style={{
            position: "absolute",
            left: logoX,
            top: logoY,
            width: bigW,
            height: bigH,
            transform: `scale(${logoScale})`,
            transformOrigin: L.align === "left" ? "left top" : "center top",
            opacity: reveal * (1 - ease.cinematicIn(progress(frame, T.endCard - 6, T.endCard + 8))),
          }}
        >
          <Logo asset={logo} width={bigW} height={bigH} reveal="scale" progress={reveal} glow={rgba(brand.accent, 0.5 * (1 - travel))} />
          {/* Light sweep across the mark. */}
          <div
            style={{
              position: "absolute",
              inset: "-20% 0",
              background: `linear-gradient(105deg, transparent 40%, rgba(255,255,255,0.45) 50%, transparent 60%)`,
              transform: `translateX(${(sweep * 2 - 1) * 120}%)`,
              opacity: sweep > 0 && sweep < 1 ? 1 : 0,
              mixBlendMode: "screen",
              pointerEvents: "none",
            }}
          />
        </div>
      ) : null}

      {/* Brand name under the mark while it is centred. */}
      {brand.name ? (
        <BoxAt box={{ x: 0, y: cy + bigH + L.unit * 0.02, width, height: L.unit * 0.1 }}>
          <div
            style={{
              fontFamily: '"SF Pro Display", -apple-system, Inter, system-ui, sans-serif',
              fontSize: L.unit * 0.05,
              fontWeight: 600,
              letterSpacing: "0.12em",
              textTransform: "uppercase",
              color: "rgba(255,255,255,0.85)",
              opacity: ease.cinematicOut(progress(frame, T.revealEnd - 16, T.revealEnd + 8)) * (1 - ease.cinematicIn(progress(frame, T.moveStart, T.moveStart + 14))),
              transform: `translateY(${(1 - ease.cinematicOut(progress(frame, T.revealEnd - 16, T.revealEnd + 8))) * L.unit * 0.02}px)`,
            }}
          >
            {brand.name}
          </div>
        </BoxAt>
      ) : null}

      <CopyBand layout={L} copy={copy} brand={brand} from={T.headline} leave={T.copyLeave} />
      <EndCard from={T.endCard} cta={cta} brand={brand} logo={logo} badges="both" scrim={0.86} />
    </AbsoluteFill>
  );
};

export const template: TemplateDefinition = {
  id: "logo-reveal",
  name: "Logo Reveal + Device",
  tagline: "The mark blooms first, then shrinks to the corner as your device scales up behind it. Ends on the store badges.",
  category: "logo",
  devices: ["iphone", "macbook"],
  durationInFrames: 300,
  aspects: ["9:16", "1:1", "16:9"],
  slots: { screens: { min: 1, max: 4, surface: "any" }, logo: "required", headline: true, subline: true, cta: true, accent: true, duration: null },
  component: Component,
};
