// GENERATED by scripts/sync-video.mjs from backend/remotion/src - do not edit here.
import { track, type TrackKeyframe } from "./keyframes";

/**
 * A camera, expressed as what it does to the world.
 *
 * `dolly` is a distance factor: 1 is rest, 2 is twice as close, 0.5 twice as
 * far. It is applied as a Z translation against the stage perspective, not
 * as a scale, so layers at different depths separate as the camera moves -
 * which is what makes a push-in feel like a camera and not a zoom.
 *
 * Orbits are degrees around the stage origin: `orbitY` walks around the
 * subject (positive = camera moves to the subject's right), `orbitX` looks
 * down on it (positive = camera above). `x`/`y` truck in stage pixels.
 */
export interface CameraState {
  dolly: number;
  orbitY: number;
  orbitX: number;
  x: number;
  y: number;
  roll: number;
  /**
   * Vertical field of view in degrees. Sets the perspective distance the
   * way a lens does: 24 is wide and dramatic, 50 is a normal lens, 85 is a
   * portrait lens that flattens the subject. 0 means "use the stage's own
   * default", which is what every template written before this does.
   */
  fov: number;
  /**
   * Depth of field. `focus` is the stage-Z the lens is focused at, and
   * `aperture` how many stage px either side stay sharp; 0 aperture means
   * everything is sharp. Applied by `depthBlur`, not by the stage itself.
   */
  focus: number;
  aperture: number;
}

export const CAMERA_REST: CameraState = {
  dolly: 1,
  orbitY: 0,
  orbitX: 0,
  x: 0,
  y: 0,
  roll: 0,
  fov: 0,
  focus: 0,
  aperture: 0,
};

/**
 * Perspective distance for a vertical field of view on a canvas of the
 * given height - the pinhole relation, so a 50deg lens on a 1920px-tall
 * frame puts the eye about 2060px from the plane.
 */
export function perspectiveFor(fov: number, height: number): number {
  const half = ((Math.max(5, Math.min(120, fov)) / 2) * Math.PI) / 180;
  return height / 2 / Math.tan(half);
}

/**
 * Blur radius for something at stage-Z `z` under the camera's focus. Zero
 * inside the aperture, growing linearly beyond it, capped so a far
 * background reads as soft rather than smeared.
 */
export function depthBlur(camera: CameraState, z: number, max = 14): number {
  if (camera.aperture <= 0) return 0;
  const distance = Math.abs(z - camera.focus);
  if (distance <= camera.aperture) return 0;
  return Math.min(max, ((distance - camera.aperture) / camera.aperture) * 3);
}

export type CameraKeyframe = TrackKeyframe<keyof CameraState>;

export function cameraAt(
  frame: number,
  keyframes: readonly CameraKeyframe[],
): CameraState {
  return {
    dolly: track(frame, keyframes, "dolly", CAMERA_REST.dolly),
    orbitY: track(frame, keyframes, "orbitY", CAMERA_REST.orbitY),
    orbitX: track(frame, keyframes, "orbitX", CAMERA_REST.orbitX),
    x: track(frame, keyframes, "x", CAMERA_REST.x),
    y: track(frame, keyframes, "y", CAMERA_REST.y),
    roll: track(frame, keyframes, "roll", CAMERA_REST.roll),
    fov: track(frame, keyframes, "fov", CAMERA_REST.fov),
    focus: track(frame, keyframes, "focus", CAMERA_REST.focus),
    aperture: track(frame, keyframes, "aperture", CAMERA_REST.aperture),
  };
}

/** Z offset that makes a point at the origin appear `dolly` times closer. */
export function dollyToZ(dolly: number, perspective: number): number {
  const factor = Math.max(0.05, dolly);
  return perspective * (1 - 1 / factor);
}

/**
 * The world transform for a camera state. Applied to a `preserve-3d`
 * container centred on the stage, under a `perspective` of the given size.
 */
export function cameraTransform(camera: CameraState, perspective: number): string {
  const z = dollyToZ(camera.dolly, perspective);
  return [
    `translate3d(${camera.x}px, ${camera.y}px, ${z}px)`,
    // CSS rotateX(+) tips the world's near side up, which reads as a camera
    // below the subject. Negate so positive orbitX is a camera above.
    `rotateX(${-camera.orbitX}deg)`,
    `rotateY(${camera.orbitY}deg)`,
    `rotateZ(${camera.roll}deg)`,
  ].join(" ");
}

/** Adds two states - a keyframed move plus a hand-held drift, typically. */
export function addCamera(a: CameraState, b: Partial<CameraState>): CameraState {
  return {
    dolly: a.dolly * (b.dolly ?? 1),
    orbitY: a.orbitY + (b.orbitY ?? 0),
    orbitX: a.orbitX + (b.orbitX ?? 0),
    x: a.x + (b.x ?? 0),
    y: a.y + (b.y ?? 0),
    roll: a.roll + (b.roll ?? 0),
    fov: b.fov ?? a.fov,
    focus: b.focus ?? a.focus,
    aperture: b.aperture ?? a.aperture,
  };
}
