// GENERATED by scripts/sync-video.mjs from backend/remotion/src - do not edit here.
import { ease, type EasingFn } from "./easing";

export interface Keyframe {
  /** Frame. */
  at: number;
  value: number;
  /** How the value *arrives* at this keyframe from the previous one. */
  easing?: EasingFn;
}

/**
 * Piecewise interpolation with a curve per segment.
 *
 *   kf(frame, [
 *     { at: 0,  value: -90 },
 *     { at: 60, value: 10, easing: ease.cinematicInOut },
 *     { at: 90, value: 6,  easing: ease.settle },
 *   ])
 *
 * Before the first keyframe the value holds; after the last it holds. A
 * segment's easing lives on its destination keyframe, which reads as "get
 * to 10 with a cinematic in-out" - the way animators write it.
 */
export function kf(frame: number, keyframes: readonly Keyframe[]): number {
  const first = keyframes[0];
  if (!first) return 0;
  if (frame <= first.at) return first.value;

  for (let index = 1; index < keyframes.length; index += 1) {
    const to = keyframes[index] as Keyframe;
    if (frame > to.at) continue;
    const from = keyframes[index - 1] as Keyframe;
    const span = to.at - from.at;
    if (span <= 0) return to.value;
    const t = (frame - from.at) / span;
    const curve = to.easing ?? ease.cinematicOut;
    return from.value + (to.value - from.value) * curve(t);
  }

  return (keyframes[keyframes.length - 1] as Keyframe).value;
}

/**
 * Multi-property keyframes: a property left out of a keyframe holds its last
 * value, so a camera move can change the orbit at frame 60 without also
 * restating the dolly.
 */
export type TrackKeyframe<K extends string> = { at: number; easing?: EasingFn } & Partial<
  Record<K, number>
>;

export function track<K extends string>(
  frame: number,
  keyframes: readonly TrackKeyframe<K>[],
  property: K,
  fallback: number,
): number {
  const defined: Keyframe[] = [];
  for (const keyframe of keyframes) {
    const value = keyframe[property];
    if (typeof value === "number") {
      defined.push(
        keyframe.easing
          ? { at: keyframe.at, value, easing: keyframe.easing }
          : { at: keyframe.at, value },
      );
    }
  }
  if (defined.length === 0) return fallback;
  return kf(frame, defined);
}
