// GENERATED by scripts/sync-video.mjs from backend/remotion/src - do not edit here.
import React from "react";
import { Placed } from "../scene/Stage";
import { MACBOOK } from "./specs";
import { Glass } from "../content/Screen";
import { rgba } from "../palette";

export interface MacBookGeometry {
  width: number;
  bezel: number;
  chin: number;
  screenWidth: number;
  screenHeight: number;
  lidHeight: number;
  deckDepth: number;
  lidThickness: number;
  deckThickness: number;
  radius: number;
}

export function macbookGeometry(width: number): MacBookGeometry {
  const bezel = width * MACBOOK.bezel;
  const chin = width * MACBOOK.chin;
  const screenWidth = width - bezel * 2;
  const screenHeight = screenWidth / MACBOOK.screenAspect;
  return {
    width,
    bezel,
    chin,
    screenWidth,
    screenHeight,
    lidHeight: screenHeight + bezel + chin,
    deckDepth: width * MACBOOK.deckDepth,
    lidThickness: width * MACBOOK.lidThickness,
    deckThickness: width * MACBOOK.deckThickness,
    radius: width * MACBOOK.cornerRadius,
  };
}

/** Lid angles in the laptop's own frame. */
export const LID_CLOSED = -90;
export const LID_OPEN = MACBOOK.openLean;

const ALUMINIUM =
  "linear-gradient(168deg, #dcdde2 0%, #b9bbc3 34%, #979aa3 68%, #cfd1d7 100%)";
const ALUMINIUM_DARK =
  "linear-gradient(180deg, #8d9099 0%, #6f727a 100%)";
const BLACK_BODY =
  "linear-gradient(160deg, #2a2a30 0%, #121215 26%, #0a0a0d 74%, #202025 100%)";

/**
 * A MacBook, built in its own 3D frame.
 *
 * Origin is the hinge: the back edge of the deck's top surface, centred.
 * +y is down, +z is toward the camera. The deck lies flat toward the camera;
 * the lid hangs off the hinge and rotates about it. `lidAngle` is that
 * rotation: -90 is shut (lid flat on the deck, aluminium up), +12 is open
 * and leaning back the way a laptop does on a desk. Between the two the
 * screen turns to face the camera as it passes 0.
 *
 * The whole thing is meant to be placed with `<Placed>` inside a `<Stage>`
 * and orbited by the camera - it is not pre-posed for one view.
 */
export const MacBook: React.FC<{
  width: number;
  lidAngle: number;
  /** Screen content, given the screen's size. */
  screen: (dims: { width: number; height: number }) => React.ReactNode;
  /** 0..1, how bright the screen is - drives the glow on the deck. */
  brightness?: number;
  /** Tint of the glow. */
  accent?: string;
  /** Extra transform applied to the whole laptop (its own idle, say). */
  transform?: string;
}> = ({ width, lidAngle, screen, brightness = 1, accent = "#8ab4ff", transform }) => {
  const g = macbookGeometry(width);

  // The screen faces the camera once the lid has passed vertical-ish; the
  // spill it throws grows with the angle and the brightness.
  const facing = Math.max(0, Math.min(1, (lidAngle + 70) / 70));
  const spill = facing * brightness;

  return (
    <div
      style={{
        position: "absolute",
        width: 0,
        height: 0,
        transformStyle: "preserve-3d",
        transform: transform ?? "none",
      }}
    >
      {/* ── Deck ─────────────────────────────────────────────── */}
      {/* Top surface: keyboard well and trackpad. Bottom of the texture is the front edge. */}
      <Placed x={0} y={0} z={g.deckDepth / 2} rotateX={90} width={g.width} height={g.deckDepth}>
        <div
          style={{
            position: "absolute",
            inset: 0,
            background: ALUMINIUM,
            borderRadius: `${g.radius * 0.6}px ${g.radius * 0.6}px ${g.radius}px ${g.radius}px`,
            overflow: "hidden",
          }}
        >
          {/* Keyboard well */}
          <div
            style={{
              position: "absolute",
              left: "9%",
              top: "12%",
              width: "82%",
              height: "46%",
              borderRadius: g.radius * 0.5,
              background: "linear-gradient(180deg, #24242a 0%, #1a1a1f 60%, #2b2b32 100%)",
              boxShadow: "inset 0 1px 2px rgba(0,0,0,0.6)",
            }}
          >
            {/* Keys: a grid of caps, drawn as two crossed gradients. */}
            <div
              style={{
                position: "absolute",
                inset: "6% 2%",
                backgroundImage:
                  "repeating-linear-gradient(90deg, rgba(255,255,255,0.07) 0 5.9%, transparent 5.9% 6.9%), repeating-linear-gradient(180deg, rgba(255,255,255,0.05) 0 15%, transparent 15% 18.5%)",
                backgroundBlendMode: "screen",
                opacity: 0.9,
              }}
            />
          </div>
          {/* Trackpad */}
          <div
            style={{
              position: "absolute",
              left: "34%",
              top: "66%",
              width: "32%",
              height: "28%",
              borderRadius: g.radius * 0.4,
              background: "linear-gradient(180deg, rgba(0,0,0,0.13) 0%, rgba(0,0,0,0.05) 100%)",
              border: "1px solid rgba(0,0,0,0.12)",
            }}
          />
          {/* Screen light landing on the deck. */}
          <div
            style={{
              position: "absolute",
              left: "-10%",
              top: "-30%",
              width: "120%",
              height: "90%",
              background: `radial-gradient(ellipse at 50% 20%, ${rgba(accent, 0.55)} 0%, transparent 65%)`,
              opacity: spill * 0.9,
              mixBlendMode: "screen",
              pointerEvents: "none",
            }}
          />
          {/* Hinge shadow */}
          <div
            style={{
              position: "absolute",
              left: 0,
              right: 0,
              top: 0,
              height: "10%",
              background: "linear-gradient(180deg, rgba(0,0,0,0.55) 0%, transparent 100%)",
            }}
          />
        </div>
      </Placed>
      {/* Front edge */}
      <Placed x={0} y={g.deckThickness / 2} z={g.deckDepth} width={g.width} height={g.deckThickness}>
        <div
          style={{
            position: "absolute",
            inset: 0,
            background: ALUMINIUM_DARK,
            borderRadius: `0 0 ${g.radius * 0.5}px ${g.radius * 0.5}px`,
          }}
        />
      </Placed>
      {/* Side edges */}
      {[-1, 1].map((side) => (
        <Placed
          key={side}
          x={(side * g.width) / 2}
          y={g.deckThickness / 2}
          z={g.deckDepth / 2}
          rotateY={90}
          width={g.deckDepth}
          height={g.deckThickness}
        >
          <div style={{ position: "absolute", inset: 0, background: ALUMINIUM_DARK }} />
        </Placed>
      ))}
      {/* Underside shadow - the deck is not floating. */}
      <Placed x={0} y={g.deckThickness + 2} z={g.deckDepth / 2} rotateX={90} width={g.width * 1.02} height={g.deckDepth * 1.02}>
        <div
          style={{
            position: "absolute",
            inset: 0,
            borderRadius: g.radius,
            background: "rgba(0,0,0,0.85)",
            filter: "blur(6px)",
          }}
        />
      </Placed>

      {/* ── Lid ──────────────────────────────────────────────── */}
      <div
        style={{
          position: "absolute",
          width: 0,
          height: 0,
          transformStyle: "preserve-3d",
          // Sits on top of the deck's thickness, then rotates about the hinge.
          transform: `translateY(${-g.deckThickness}px) rotateX(${lidAngle}deg)`,
        }}
      >
        {/* Front: bezel + screen */}
        <Placed x={0} y={-g.lidHeight / 2} z={0} width={g.width} height={g.lidHeight}>
          <div
            style={{
              position: "absolute",
              inset: 0,
              backfaceVisibility: "hidden",
              background: BLACK_BODY,
              borderRadius: `${g.radius}px ${g.radius}px ${g.radius * 0.5}px ${g.radius * 0.5}px`,
              boxSizing: "border-box",
              padding: `${g.bezel}px ${g.bezel}px ${g.chin}px`,
            }}
          >
            <div
              style={{
                position: "relative",
                width: g.screenWidth,
                height: g.screenHeight,
                borderRadius: g.radius * 0.5,
                overflow: "hidden",
                background: "#000",
              }}
            >
              <div style={{ position: "absolute", inset: 0, opacity: brightness }}>
                {screen({ width: g.screenWidth, height: g.screenHeight })}
              </div>
              <Glass angle={104 + lidAngle * 0.4} strength={0.1} />
            </div>
            {/* Chin wordmark */}
            <div
              style={{
                position: "absolute",
                left: 0,
                right: 0,
                bottom: g.chin * 0.32,
                textAlign: "center",
                fontFamily: '"SF Pro Display", -apple-system, Inter, system-ui, sans-serif',
                fontSize: g.chin * 0.36,
                letterSpacing: "0.16em",
                color: "rgba(255,255,255,0.22)",
              }}
            >
              MacBook Pro
            </div>
          </div>
        </Placed>
        {/* Back: the aluminium the camera sees while the lid is shut. */}
        <Placed x={0} y={-g.lidHeight / 2} z={-g.lidThickness} rotateY={180} width={g.width} height={g.lidHeight}>
          <div
            style={{
              position: "absolute",
              inset: 0,
              backfaceVisibility: "hidden",
              background: ALUMINIUM,
              borderRadius: `${g.radius}px ${g.radius}px ${g.radius * 0.5}px ${g.radius * 0.5}px`,
            }}
          >
            <div
              style={{
                position: "absolute",
                left: "50%",
                top: "50%",
                width: g.width * 0.13,
                height: g.width * 0.13,
                marginLeft: -g.width * 0.065,
                marginTop: -g.width * 0.065,
                borderRadius: "50%",
                background: "rgba(255,255,255,0.55)",
                boxShadow: "inset 0 2px 8px rgba(0,0,0,0.18)",
              }}
            />
          </div>
        </Placed>
        {/* Lid edges: top and sides, so the lid has thickness from any angle. */}
        <Placed x={0} y={-g.lidHeight} z={-g.lidThickness / 2} rotateX={90} width={g.width} height={g.lidThickness}>
          <div style={{ position: "absolute", inset: 0, background: ALUMINIUM_DARK }} />
        </Placed>
        {[-1, 1].map((side) => (
          <Placed
            key={side}
            x={(side * g.width) / 2}
            y={-g.lidHeight / 2}
            z={-g.lidThickness / 2}
            rotateY={90}
            width={g.lidThickness}
            height={g.lidHeight}
          >
            <div style={{ position: "absolute", inset: 0, background: ALUMINIUM_DARK }} />
          </Placed>
        ))}
      </div>
    </div>
  );
};
