import fs from "node:fs";
import path from "node:path";
import * as XLSX from "xlsx";

export const EBAY_FR_COLUMNS = [
  "Action",
  "Custom label (SKU)",
  "Category ID",
  "Category Name",
  "Title",
  "Subtitle",
  "P:EAN",
  "Start price",
  "Quantity",
  "Item photo URL",
  "Condition ID",
  "Condition description",
  "Description",
  "Format",
  "Duration",
  "Location",
  "Country",
  "Postal code",
  "Shipping profile name",
  "Return profile name",
  "Payment profile name",
  "Brand",
  "Manufacturer",
  "MPN",
  "Model",
  "Product type",
  "Sold item name",
  "Compatible brand",
  "Compatible device",
  "Compatible model number",
  "Color",
  "Material",
  "Type",
  "Unit quantity",
  "Unit type",
  "Item specifics",
] as const;

type TemplateRow = Record<(typeof EBAY_FR_COLUMNS)[number], string>;

function baseRow(overrides: Partial<TemplateRow>): TemplateRow {
  const row = Object.fromEntries(
    EBAY_FR_COLUMNS.map((col) => [col, ""]),
  ) as TemplateRow;

  return {
    ...row,
    Action: "Add",
    Format: "FixedPrice",
    Duration: "GTC",
    Location: "Paris",
    Country: "FR",
    "Postal code": "75001",
    "Shipping profile name": "Standard",
    "Return profile name": "30 jours",
    "Payment profile name": "eBay Payments",
    Quantity: "1",
    "Unit quantity": "1",
    "Unit type": "Unité",
    "Condition ID": "3000",
    "Condition description": "Occasion",
    ...overrides,
  };
}

export const EXAMPLE_PRODUCTS: TemplateRow[] = [
  baseRow({
    "Custom label (SKU)": "TEST-001",
    "Category ID": "175673",
    "Category Name": "Cartes mères",
    Title: "Carte mère MacBook Pro 16 A2141 820-01779-A",
    "Start price": "189.99",
    Brand: "Apple",
    Manufacturer: "Apple",
    MPN: "820-01779-A",
    Model: "A2141",
    "Product type": "Logic Board",
    "Sold item name": "Logic Board",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Pro 16",
    "Compatible model number": "A2141",
    Color: "Green",
    Material: "PCB",
    Type: "Logic Board",
    "Item specifics":
      "Brand=Apple|MPN=820-01779-A|Model=A2141|Type=Logic Board|Color=Green",
    Description: "Carte mère d'origine testée, référence 820-01779-A.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-002",
    "Category ID": "80053",
    "Category Name": "Écrans LCD",
    Title: "Écran LCD MacBook Air 13 A2337 Remplacement",
    "Start price": "129.50",
    Brand: "Apple",
    MPN: "661-17578",
    Model: "A2337",
    "Product type": "Screen Replacement",
    "Sold item name": "Screen Replacement",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Air 13",
    "Compatible model number": "A2337",
    Color: "Noir",
    Type: "LCD Panel",
    "Item specifics":
      "Brand=Apple|Model=A2337|Type=Screen Replacement|Color=Black",
    Description: "Dalle LCD de remplacement pour MacBook Air M1.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-003",
    "Category ID": "176970",
    "Category Name": "Batteries",
    Title: "Batterie MacBook Pro 15 A1707 020-00977",
    "Start price": "59.00",
    Brand: "Apple",
    MPN: "020-00977",
    Model: "A1707",
    "Product type": "Battery",
    "Sold item name": "Battery",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Pro 15",
    "Compatible model number": "A1707",
    Material: "Lithium-ion",
    Type: "Battery",
    "Item specifics": "Brand=Apple|MPN=020-00977|Model=A1707|Type=Battery",
    Description: "Batterie compatible MacBook Pro 15 pouces Touch Bar.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-004",
    "Category ID": "176970",
    "Category Name": "Connecteurs",
    Title: "Connecteur port charge USB-C MacBook Pro A1990",
    "Start price": "24.90",
    Brand: "Apple",
    MPN: "820-00850-A",
    Model: "A1990",
    "Product type": "Charging Port",
    "Sold item name": "Charging Port",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Pro 13",
    "Compatible model number": "A1990",
    Type: "USB-C Port",
    "Item specifics":
      "Brand=Apple|MPN=820-00850-A|Type=Charging Port|Model=A1990",
    Description: "Connecteur de charge USB-C avec nappe incluse.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-005",
    "Category ID": "176970",
    "Category Name": "Nappes flex",
    Title: "Nappe flex trackpad MacBook Pro 13 A1708",
    "Start price": "14.50",
    Brand: "Apple",
    MPN: "821-01021-A",
    Model: "A1708",
    "Product type": "Flex Cable",
    "Sold item name": "Flex Cable",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Pro 13",
    "Compatible model number": "A1708",
    Type: "Flex Cable",
    "Item specifics": "Brand=Apple|MPN=821-01021-A|Type=Flex Cable",
    Description: "Nappe flex pour trackpad MacBook Pro 13 2016-2017.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-006",
    "Category ID": "176970",
    "Category Name": "Caméras",
    Title: "Caméra FaceTime MacBook Air A2179",
    "Start price": "19.99",
    Brand: "Apple",
    MPN: "821-02106",
    Model: "A2179",
    "Product type": "Camera",
    "Sold item name": "Camera Module",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Air 13",
    "Compatible model number": "A2179",
    Type: "Webcam",
    "Item specifics": "Brand=Apple|Model=A2179|Type=Camera",
    Description: "Module caméra FaceTime HD d'origine.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-007",
    "Category ID": "176970",
    "Category Name": "Haut-parleurs",
    Title: "Haut-parleurs MacBook Pro 16 A2141 paire",
    "Start price": "34.00",
    Brand: "Apple",
    MPN: "923-04201",
    Model: "A2141",
    "Product type": "Speaker",
    "Sold item name": "Speaker Set",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Pro 16",
    "Compatible model number": "A2141",
    Type: "Speaker",
    "Item specifics": "Brand=Apple|Model=A2141|Type=Speaker",
    Description: "Paire de haut-parleurs gauche et droite.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-008",
    "Category ID": "176970",
    "Category Name": "Claviers",
    Title: "Clavier AZERTY MacBook Pro 14 A2442",
    "Start price": "89.00",
    Brand: "Apple",
    MPN: "661-25830",
    Model: "A2442",
    "Product type": "Keyboard",
    "Sold item name": "Keyboard",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Pro 14",
    "Compatible model number": "A2442",
    Color: "Noir",
    Type: "Keyboard",
    "Item specifics": "Brand=Apple|Model=A2442|Type=Keyboard|Color=Black",
    Description: "Clavier rétroéclairé AZERTY avec Touch ID.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-009",
    "Category ID": "176970",
    "Category Name": "Trackpads",
    Title: "Trackpad Force Touch MacBook Pro 13 A2289",
    "Start price": "45.00",
    Brand: "Apple",
    MPN: "661-15729",
    Model: "A2289",
    "Product type": "Trackpad",
    "Sold item name": "Trackpad",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Pro 13",
    "Compatible model number": "A2289",
    Color: "Gris sidéral",
    Type: "Trackpad",
    "Item specifics": "Brand=Apple|Model=A2289|Type=Trackpad",
    Description: "Trackpad Force Touch gris sidéral.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-010",
    "Category ID": "176970",
    "Category Name": "Ventilateurs",
    Title: "Ventilateur gauche MacBook Pro 15 A1707",
    "Start price": "22.50",
    Brand: "Apple",
    MPN: "923-01314",
    Model: "A1707",
    "Product type": "Fan",
    "Sold item name": "Cooling Fan",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Pro 15",
    "Compatible model number": "A1707",
    Type: "Fan",
    "Item specifics": "Brand=Apple|Model=A1707|Type=Fan",
    Description: "Ventilateur de refroidissement côté gauche.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-011",
    "Category ID": "176970",
    "Category Name": "Chargeurs",
    Title: "Chargeur USB-C 61W MacBook compatible",
    "Start price": "39.90",
    Brand: "Apple",
    MPN: "MNF72",
    Model: "MNF72LL/A",
    "Product type": "Charger",
    "Sold item name": "Power Adapter",
    Type: "Charger",
    "Item specifics": "Brand=Apple|MPN=MNF72|Type=Charger|Wattage=61W",
    Description: "Adaptateur secteur USB-C 61W pour MacBook.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-012",
    "Category ID": "176970",
    "Category Name": "SSD",
    Title: "SSD NVMe 512Go MacBook Pro A1989",
    "Start price": "79.00",
    Brand: "Apple",
    MPN: "655-01036",
    Model: "A1989",
    "Product type": "SSD",
    "Sold item name": "Solid State Drive",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Pro 13",
    "Compatible model number": "A1989",
    Type: "SSD",
    "Item specifics": "Brand=Apple|Model=A1989|Type=SSD|Capacity=512GB",
    Description: "SSD NVMe 512 Go souder pour MacBook Pro.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-013",
    "Category ID": "176970",
    "Category Name": "Cartes WiFi",
    Title: "Carte WiFi Bluetooth MacBook Air A1466",
    "Start price": "18.00",
    Brand: "Apple",
    MPN: "607-8969",
    Model: "A1466",
    "Product type": "WiFi Card",
    "Sold item name": "WiFi Card",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Air 13",
    "Compatible model number": "A1466",
    Type: "WiFi Card",
    "Item specifics": "Brand=Apple|Model=A1466|Type=WiFi Card",
    Description: "Carte WiFi/Bluetooth Broadcom d'origine.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-014",
    "Category ID": "176970",
    "Category Name": "Coques",
    Title: "Boîtier inférieur MacBook Pro 13 A2251",
    "Start price": "49.00",
    Brand: "Apple",
    MPN: "661-17529",
    Model: "A2251",
    "Product type": "Case",
    "Sold item name": "Bottom Case",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Pro 13",
    "Compatible model number": "A2251",
    Color: "Gris sidéral",
    Material: "Aluminium",
    Type: "Case",
    "Item specifics": "Brand=Apple|Model=A2251|Type=Case|Color=Space Gray",
    Description: "Coque inférieure aluminium gris sidéral.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-015",
    "Category ID": "176970",
    "Category Name": "Dissipateurs",
    Title: "Dissipateur thermique MacBook Pro 16 A2141",
    "Start price": "27.00",
    Brand: "Apple",
    MPN: "923-04200",
    Model: "A2141",
    "Product type": "Heatsink",
    "Sold item name": "Heatsink",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Pro 16",
    "Compatible model number": "A2141",
    Material: "Cuivre",
    Type: "Heatsink",
    "Item specifics": "Brand=Apple|Model=A2141|Type=Heatsink|Material=Copper",
    Description: "Dissipateur thermique CPU/GPU.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-016",
    "Category ID": "175673",
    "Category Name": "Cartes mères",
    Title: "Carte mère MacBook Pro 13 A2159 820-01646-A",
    "Start price": "149.00",
    Brand: "Apple",
    Manufacturer: "Apple",
    MPN: "01646-A",
    Model: "A2159",
    "Product type": "Logic Board",
    "Sold item name": "Logic Board",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Pro 13",
    "Compatible model number": "A2159",
    Color: "Vert",
    Type: "Logic Board",
    "Item specifics":
      "Brand=Apple|MPN=01646-A|Model=A2159|Type=Logic Board|Color=Green",
    Description: "Carte mère référence 820-01646-A / 01646-A.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-017",
    "Category ID": "80053",
    "Category Name": "Écrans LCD",
    Title: "Écran complet MacBook Pro 14 A2442",
    "Start price": "299.00",
    Brand: "Apple",
    MPN: "661-25828",
    Model: "A2442",
    "Product type": "Screen Replacement",
    "Sold item name": "Screen Replacement",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Pro 14",
    "Compatible model number": "A2442",
    Type: "Display Assembly",
    "Item specifics": "Brand=Apple|Model=A2442|Type=Screen Replacement",
    Description: "Module écran complet Liquid Retina XDR.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-018",
    "Category ID": "176970",
    "Category Name": "Batteries",
    Title: "Batterie MacBook Air M2 A2681",
    "Start price": "69.00",
    Brand: "Apple",
    MPN: "A2681-BAT",
    Model: "A2681",
    "Product type": "Battery",
    "Sold item name": "Battery",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Air 15",
    "Compatible model number": "A2681",
    Type: "Battery",
    "Item specifics": "Brand=Apple|Model=A2681|Type=Battery",
    Description: "Batterie pour MacBook Air 15 M2.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-019",
    "Category ID": "176970",
    "Category Name": "Nappes flex",
    Title: "Nappe écran MAINFPC_V3.1 MacBook Pro 15",
    "Start price": "32.00",
    Brand: "Apple",
    MPN: "MAINFPC_V3.1",
    Model: "A1990",
    "Product type": "Flex Cable",
    "Sold item name": "Display Flex Cable",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Pro 15",
    "Compatible model number": "A1990",
    Type: "Flex Cable",
    "Item specifics": "Brand=Apple|MPN=MAINFPC_V3.1|Type=Flex Cable",
    Description: "Nappe vidéo référence MAINFPC_V3.1.",
  }),
  baseRow({
    "Custom label (SKU)": "TEST-020",
    "Category ID": "176970",
    "Category Name": "Connecteurs",
    Title: "Connecteur audio jack MacBook Pro M6100",
    "Start price": "16.50",
    Brand: "Apple",
    MPN: "M6100",
    Model: "A1502",
    "Product type": "Connector",
    "Sold item name": "Audio Jack",
    "Compatible brand": "Apple",
    "Compatible device": "MacBook Pro 13",
    "Compatible model number": "A1502",
    Type: "Audio Connector",
    "Item specifics": "Brand=Apple|MPN=M6100|Type=Connector",
    Description: "Connecteur jack audio 3.5mm avec nappe.",
  }),
];

function rowsToCsv(rows: TemplateRow[]): string {
  const header = EBAY_FR_COLUMNS.join(",");
  const body = rows
    .map((row) =>
      EBAY_FR_COLUMNS.map((col) => {
        const value = row[col] ?? "";
        const escaped = value.replace(/"/g, '""');
        return value.includes(",") || value.includes('"') || value.includes("\n")
          ? `"${escaped}"`
          : escaped;
      }).join(","),
    )
    .join("\n");

  return `${header}\n${body}\n`;
}

function writeXlsx(filePath: string, rows: TemplateRow[]): void {
  const worksheet = XLSX.utils.json_to_sheet(rows, {
    header: [...EBAY_FR_COLUMNS],
  });
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Import eBay");
  XLSX.writeFile(workbook, filePath);
}

function main(): void {
  const templatesDir = path.resolve(process.cwd(), "public", "templates");
  fs.mkdirSync(templatesDir, { recursive: true });

  const emptyTemplate = baseRow({});

  fs.writeFileSync(
    path.join(templatesDir, "modele-import-ebay.csv"),
    rowsToCsv([emptyTemplate]),
    "utf8",
  );
  writeXlsx(path.join(templatesDir, "modele-import-ebay.xlsx"), [emptyTemplate]);

  fs.writeFileSync(
    path.join(templatesDir, "exemple-import-ebay.csv"),
    rowsToCsv(EXAMPLE_PRODUCTS),
    "utf8",
  );
  writeXlsx(
    path.join(templatesDir, "exemple-import-ebay.xlsx"),
    EXAMPLE_PRODUCTS,
  );

  console.log(`Generated 4 template files in ${templatesDir}`);
}

main();
