#!/usr/bin/env node
/**
 * Mirrors backend/remotion/src into frontend/src/video.
 *
 * The Remotion module is the source of truth for templates; the frontend
 * needs the same code to play them in the browser. It is copied, and the
 * copy committed, rather than shared as a package: Vercel builds from
 * frontend/ and cannot see ../backend, Railway builds from backend/ and
 * cannot see ../frontend. A committed copy deploys without touching either
 * platform's settings - the same choice already made for the types.
 *
 *   node scripts/sync-video.mjs          copy
 *   node scripts/sync-video.mjs --check  exit 1 if the copy is stale
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const source = path.join(root, "backend", "remotion", "src");
const target = path.join(root, "frontend", "src", "video");
const check = process.argv.includes("--check");

const HEADER =
  "// GENERATED by scripts/sync-video.mjs from backend/remotion/src - do not edit here.\n";

function walk(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (/\.(ts|tsx)$/.test(entry.name)) out.push(full);
  }
  return out;
}

if (!fs.existsSync(source)) {
  console.error(`sync-video: ${source} does not exist here; nothing to sync.`);
  process.exit(check ? 0 : 1);
}

// index.ts calls registerRoot, which only makes sense in the Remotion
// bundle; the frontend imports Root and the registry directly.
const files = walk(source).filter((file) => path.relative(source, file) !== "index.ts");
const expected = new Map();
for (const file of files) {
  const relative = path.relative(source, file);
  expected.set(relative, HEADER + fs.readFileSync(file, "utf8"));
}

let stale = [];
if (fs.existsSync(target)) {
  for (const file of walk(target)) {
    const relative = path.relative(target, file);
    if (!expected.has(relative)) stale.push(`extra: ${relative}`);
  }
}
for (const [relative, content] of expected) {
  const dest = path.join(target, relative);
  if (!fs.existsSync(dest) || fs.readFileSync(dest, "utf8") !== content) {
    stale.push(`changed: ${relative}`);
  }
}

if (check) {
  if (stale.length > 0) {
    console.error("frontend/src/video is out of date with backend/remotion/src:");
    for (const line of stale) console.error(`  ${line}`);
    console.error("Run: npm run video:sync");
    process.exit(1);
  }
  console.log("frontend/src/video is in sync.");
  process.exit(0);
}

fs.rmSync(target, { recursive: true, force: true });
for (const [relative, content] of expected) {
  const dest = path.join(target, relative);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, content);
}
console.log(`synced ${expected.size} files -> frontend/src/video`);
