// GENERATED by scripts/sync-video.mjs from backend/remotion/src - do not edit here.
import type { ImageAsset } from "../../engine/types";

/**
 * Pure drawing for a device screen: the display area inset from the
 * glass, rounded, with the screenshot fitted and scrolled, and a second
 * screenshot crossfading in when asked. Everything is a function of its
 * arguments, so the same frame paints the same pixels.
 */

export interface ScreenShape {
  /** Canvas size, px. Aspect matches the glass mesh. */
  width: number;
  height: number;
  /** Display inset from the glass edge, px. */
  inset: number;
  /** Display corner radius, px. */
  radius: number;
  /** Dynamic Island, px. null for devices without one. */
  island: { width: number; height: number; top: number } | null;
}

/** iPhone 15 Pro: glass 67.6 x 143.8 mm, display inset ~1.6 mm, radius ~10 mm. */
export function iphoneScreenShape(longEdge: number): ScreenShape {
  const height = longEdge;
  const width = Math.round((longEdge * 67.59) / 143.77);
  const mm = width / 67.59;
  return {
    width,
    height,
    inset: 1.6 * mm,
    radius: 10 * mm,
    island: { width: 24.5 * mm, height: 7.4 * mm, top: 3.1 * mm },
  };
}

/** A laptop display: thin bezel, small radius, no island. */
export function laptopScreenShape(longEdge: number, aspect: number): ScreenShape {
  const width = longEdge;
  const height = Math.round(longEdge / aspect);
  return { width, height, inset: 0, radius: width * 0.012, island: null };
}

const MAX_TRAVEL = 1.15;

export interface DrawLayer {
  image: HTMLImageElement | null;
  asset: ImageAsset;
  /** 0..1 */
  scroll: number;
  zoom: number;
  opacity: number;
}

function roundedRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number): void {
  const radius = Math.min(r, w / 2, h / 2);
  ctx.beginPath();
  ctx.moveTo(x + radius, y);
  ctx.arcTo(x + w, y, x + w, y + h, radius);
  ctx.arcTo(x + w, y + h, x, y + h, radius);
  ctx.arcTo(x, y + h, x, y, radius);
  ctx.arcTo(x, y, x + w, y, radius);
  ctx.closePath();
}

function drawFitted(ctx: CanvasRenderingContext2D, layer: DrawLayer, x: number, y: number, w: number, h: number): void {
  const { image, asset, scroll, zoom, opacity } = layer;
  if (!image || opacity <= 0) return;
  const ratio = asset.width > 0 && asset.height > 0 ? asset.height / asset.width : image.height / image.width;
  let dw: number;
  let dh: number;
  let dx = x;
  let dy = y;
  if (ratio >= h / w) {
    dw = w;
    dh = w * ratio;
    const overflow = dh - h;
    dy = y - Math.min(overflow, h * MAX_TRAVEL) * scroll;
  } else {
    dh = h;
    dw = h / ratio;
    dx = x + (w - dw) / 2;
  }
  ctx.save();
  ctx.globalAlpha = opacity;
  if (zoom !== 1) {
    const cx = x + w / 2;
    const cy = y + h * 0.4;
    ctx.translate(cx, cy);
    ctx.scale(zoom, zoom);
    ctx.translate(-cx, -cy);
  }
  ctx.drawImage(image, dx, dy, dw, dh);
  ctx.restore();
}

/**
 * Paints the screen. `layers` are drawn in order inside the display;
 * pass the outgoing screenshot first and the incoming one second with
 * its opacity rising for a crossfade.
 */
export function drawScreen(
  ctx: CanvasRenderingContext2D,
  shape: ScreenShape,
  layers: DrawLayer[],
  options: { dim?: number; off?: boolean } = {},
): void {
  const { width, height, inset, radius, island } = shape;
  ctx.save();
  ctx.globalAlpha = 1;
  ctx.fillStyle = "#050507";
  ctx.fillRect(0, 0, width, height);

  if (!options.off) {
    roundedRect(ctx, inset, inset, width - inset * 2, height - inset * 2, radius);
    ctx.clip();
    ctx.fillStyle = "#0a0a0c";
    ctx.fillRect(inset, inset, width - inset * 2, height - inset * 2);
    for (const layer of layers) drawFitted(ctx, layer, inset, inset, width - inset * 2, height - inset * 2);
    if (options.dim && options.dim > 0) {
      ctx.fillStyle = `rgba(0,0,0,${options.dim})`;
      ctx.fillRect(0, 0, width, height);
    }
  }
  ctx.restore();

  if (island) {
    ctx.fillStyle = "#000";
    roundedRect(ctx, (width - island.width) / 2, inset + island.top, island.width, island.height, island.height / 2);
    ctx.fill();
  }
}
