// GENERATED by scripts/sync-video.mjs from backend/remotion/src - do not edit here.
import type { AspectRatio } from "./types";

export const FPS = 30;

export const ASPECT_RATIOS: AspectRatio[] = ["9:16", "16:9", "1:1"];

/** Authoring size. The renderer scales down from here, never up. */
export const ASPECT_DIMENSIONS: Record<
  AspectRatio,
  { width: number; height: number }
> = {
  "9:16": { width: 1080, height: 1920 },
  "16:9": { width: 1920, height: 1080 },
  "1:1": { width: 1080, height: 1080 },
};

export const ASPECT_LABELS: Record<AspectRatio, string> = {
  "9:16": "Vertical · Reels, TikTok, Shorts",
  "16:9": "Landscape · YouTube, web",
  "1:1": "Square · Feed",
};

/** `9:16` → `9x16`: the form that survives a URL and a filename. */
export function aspectKey(aspect: AspectRatio): string {
  return aspect.replace(":", "x");
}

export function parseAspect(value: string): AspectRatio | null {
  const normalised = value.replace("x", ":");
  return (ASPECT_RATIOS as string[]).includes(normalised)
    ? (normalised as AspectRatio)
    : null;
}

/** One Remotion composition per template per aspect. */
export function compositionId(templateId: string, aspect: AspectRatio): string {
  return `${templateId}--${aspectKey(aspect)}`;
}

export function aspectOf(width: number, height: number): AspectRatio {
  const ratio = width / height;
  if (ratio > 1.15) return "16:9";
  if (ratio < 0.9) return "9:16";
  return "1:1";
}
