// GENERATED by scripts/sync-video.mjs from backend/remotion/src - do not edit here.
import { TEMPLATES } from "../templates";
import { compositionId } from "./aspect";
import type { AspectRatio, TemplateDefinition } from "./types";

export { TEMPLATES };

export function getTemplate(id: string): TemplateDefinition | null {
  return TEMPLATES.find((template) => template.id === id) ?? null;
}

/** Everything a client needs to list and validate against, minus the component. */
export type TemplateSummary = Omit<TemplateDefinition, "component">;

export function summarize(template: TemplateDefinition): TemplateSummary {
  return {
    id: template.id,
    name: template.name,
    tagline: template.tagline,
    category: template.category,
    devices: template.devices,
    durationInFrames: template.durationInFrames,
    aspects: template.aspects,
    slots: template.slots,
  };
}

export function listTemplates(): TemplateSummary[] {
  return TEMPLATES.map(summarize);
}

/** Reverse of `compositionId`. */
export function parseCompositionId(
  id: string,
): { template: TemplateDefinition; aspect: AspectRatio } | null {
  for (const template of TEMPLATES) {
    for (const aspect of template.aspects) {
      if (compositionId(template.id, aspect) === id) return { template, aspect };
    }
  }
  return null;
}
