// GENERATED by scripts/sync-video.mjs from backend/remotion/src - do not edit here.
import React from "react";
import type { CanvasTexture } from "three";
import { IPhone3D } from "./IPhone3D";
import { MacBook3D } from "./MacBook3D";

export type Device3DType = "iphone" | "macbook";

export interface DeviceProps {
  type: Device3DType;
  screen: CanvasTexture;
  brightness?: number;
  position?: [number, number, number];
  rotation?: [number, number, number];
  scale?: number;
  /** MacBook only: lid angle in degrees, 0 closed .. -100 open. */
  lidAngle?: number;
}

/** One entry point for every device the engine knows. */
export const Device: React.FC<DeviceProps> = ({ type, lidAngle, ...rest }) => {
  if (type === "macbook") return <MacBook3D lidAngle={lidAngle ?? -100} {...rest} />;
  return <IPhone3D {...rest} />;
};
