// GENERATED by scripts/sync-video.mjs from backend/remotion/src - do not edit here.
import React from "react";
import { AbsoluteFill, Img, useCurrentFrame, useVideoConfig } from "remotion";
import { ease, progress, stagger } from "../motion/easing";
import { rgba } from "../palette";
import { COPY_FONT } from "./Copy";
import { Logo } from "./Logo";
import { StoreBadges } from "./StoreBadges";
import type { Brand, CallToAction, ImageAsset } from "../types";

/**
 * The last beat: where to go, spelled out. Logo, headline, link, QR code,
 * optional store badges, then a fade to black so the loop never cuts on a
 * bright frame.
 *
 * Screen-space, above the Stage. `from` is the frame it starts fading in.
 */
export const EndCard: React.FC<{
  from: number;
  cta: CallToAction | null;
  brand: Brand;
  logo: ImageAsset | null;
  badges?: "none" | "app" | "both";
  /** Scrim darkness at full, 0..1. */
  scrim?: number;
}> = ({ from, cta, brand, logo, badges = "none", scrim = 0.78 }) => {
  const frame = useCurrentFrame();
  const { width, height, durationInFrames, fps } = useVideoConfig();
  const unit = Math.min(width, height);
  const local = frame - from;
  if (local < 0) return null;

  // A slow, symmetric fade: on a light set the scrim is the biggest change
  // in the whole piece, and a fast-start curve reads as a cut.
  const entry = ease.smooth(progress(local, 0, Math.round(fps * 0.9)));
  const blackout = ease.cinematicIn(
    progress(frame, durationInFrames - Math.round(fps * 0.4), durationInFrames),
  );

  const rise = (order: number): React.CSSProperties => {
    const start = stagger(order, 5);
    const p = ease.cinematicOut(progress(local, start, start + 16));
    return { opacity: p, transform: `translateY(${(1 - p) * unit * 0.03}px)` };
  };

  const headline = cta?.headline ?? brand.name;

  return (
    <AbsoluteFill style={{ pointerEvents: "none" }}>
      <AbsoluteFill style={{ backgroundColor: `rgba(0,0,0,${scrim * entry})` }} />

      <AbsoluteFill
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          gap: unit * 0.028,
          padding: unit * 0.08,
          fontFamily: COPY_FONT,
          textAlign: "center",
        }}
      >
        {logo ? (
          <div style={rise(0)}>
            <Logo asset={logo} width={unit * 0.28} height={unit * 0.14} reveal="none" glow={rgba(brand.accent, 0.35)} />
          </div>
        ) : null}

        <div
          style={{
            ...rise(1),
            fontSize: unit * 0.062,
            fontWeight: 700,
            letterSpacing: "-0.03em",
            lineHeight: 1.05,
            color: "#fff",
            maxWidth: "88%",
            ...({ textWrap: "balance" } as React.CSSProperties),
          }}
        >
          {headline}
        </div>

        {cta?.qrCode ? (
          <div
            style={{
              ...rise(2),
              padding: unit * 0.016,
              borderRadius: unit * 0.024,
              background: rgba(brand.accent, 0.14),
              border: `1px solid ${rgba(brand.accent, 0.4)}`,
              lineHeight: 0,
            }}
          >
            <Img src={cta.qrCode} style={{ width: unit * 0.22, height: unit * 0.22 }} />
          </div>
        ) : null}

        {cta ? (
          <div
            style={{
              ...rise(3),
              fontSize: unit * 0.026,
              fontFamily: 'ui-monospace, "SF Mono", Menlo, monospace',
              color: brand.accent,
              wordBreak: "break-all",
              maxWidth: "86%",
            }}
          >
            {cta.url}
          </div>
        ) : null}

        {badges !== "none" ? (
          <div style={{ ...rise(4), marginTop: unit * 0.01 }}>
            <StoreBadges height={unit * 0.056} appStore googlePlay={badges === "both"} />
          </div>
        ) : null}

        {cta?.qrCode ? (
          <div
            style={{
              ...rise(5),
              fontSize: unit * 0.018,
              letterSpacing: "0.08em",
              textTransform: "uppercase",
              color: "rgba(255,255,255,0.55)",
            }}
          >
            {cta.hint}
          </div>
        ) : null}
      </AbsoluteFill>

      <AbsoluteFill style={{ backgroundColor: `rgba(0,0,0,${blackout})` }} />
    </AbsoluteFill>
  );
};
