// GENERATED by scripts/sync-video.mjs from backend/remotion/src - do not edit here.
import React from "react";
import { COPY_FONT } from "./Copy";

/**
 * Store badges drawn in CSS. Deliberately generic - no platform logo
 * glyphs, which are trademarked and would need the platform's own artwork
 * - but shaped and set the way people expect, which is what makes them read
 * as badges at a glance.
 */
const Badge: React.FC<{ eyebrow: string; label: string; height: number; icon: React.ReactNode }> = ({
  eyebrow,
  label,
  height,
  icon,
}) => (
  <div
    style={{
      display: "flex",
      alignItems: "center",
      gap: height * 0.16,
      height,
      padding: `0 ${height * 0.28}px 0 ${height * 0.2}px`,
      borderRadius: height * 0.2,
      background: "#000",
      border: "1px solid rgba(255,255,255,0.35)",
      color: "#fff",
      fontFamily: COPY_FONT,
      whiteSpace: "nowrap",
    }}
  >
    <div style={{ width: height * 0.5, height: height * 0.5, display: "grid", placeItems: "center" }}>
      {icon}
    </div>
    <div style={{ display: "flex", flexDirection: "column", lineHeight: 1 }}>
      <span style={{ fontSize: height * 0.2, letterSpacing: "0.02em", opacity: 0.85 }}>{eyebrow}</span>
      <span style={{ fontSize: height * 0.4, fontWeight: 600, letterSpacing: "-0.02em", marginTop: height * 0.04 }}>
        {label}
      </span>
    </div>
  </div>
);

const AppleGlyph: React.FC<{ size: number }> = ({ size }) => (
  <div
    style={{
      width: size * 0.8,
      height: size * 0.9,
      borderRadius: "48% 48% 44% 44% / 60% 60% 40% 40%",
      background: "#fff",
    }}
  />
);

const PlayGlyph: React.FC<{ size: number }> = ({ size }) => (
  <div
    style={{
      width: 0,
      height: 0,
      borderTop: `${size * 0.42}px solid transparent`,
      borderBottom: `${size * 0.42}px solid transparent`,
      borderLeft: `${size * 0.75}px solid #34d399`,
      marginLeft: size * 0.12,
    }}
  />
);

export const StoreBadges: React.FC<{
  height: number;
  appStore?: boolean;
  googlePlay?: boolean;
  gap?: number;
}> = ({ height, appStore = true, googlePlay = true, gap }) => (
  <div style={{ display: "flex", gap: gap ?? height * 0.3, alignItems: "center" }}>
    {appStore ? (
      <Badge eyebrow="Download on the" label="App Store" height={height} icon={<AppleGlyph size={height * 0.5} />} />
    ) : null}
    {googlePlay ? (
      <Badge eyebrow="GET IT ON" label="Google Play" height={height} icon={<PlayGlyph size={height * 0.5} />} />
    ) : null}
  </div>
);
