import { createBrowserClient } from "@supabase/ssr";

export function createClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

  if (!url || !anonKey) {
    throw new Error("Missing Supabase environment variables");
  }

  // We rely on our own row types from `types/database.ts` and keep Supabase client
  // typing permissive to avoid missing Insert/Update shapes.
  // Supabase's autogenerated Database typing usually includes Insert/Update
  // shapes; our project uses Row types only. We keep client typing permissive.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return createBrowserClient<any>(url, anonKey);
}
