// GENERATED by scripts/sync-video.mjs from backend/remotion/src - do not edit here.
import React from "react";
import { AbsoluteFill, useCurrentFrame, useVideoConfig } from "remotion";
import { Environment } from "../../engine/scene/Environment";
import { Stage, Placed } from "../../engine/scene/Stage";
import { ContactShadow, ScreenSpill, Surface } from "../../engine/scene/Floor";
import { MacBook, LID_OPEN, macbookGeometry } from "../../engine/devices/MacBook";
import { ScreenSequence } from "../../engine/content/ScreenSequence";
import { EndCard } from "../../engine/content/EndCard";
import { addCamera, cameraAt } from "../../engine/motion/camera";
import { kf } from "../../engine/motion/keyframes";
import { drift, DRIFT_PERIODS, ease, progress } from "../../engine/motion/easing";
import { layoutFor } from "../../engine/layout";
import { rgba } from "../../engine/palette";
import { CopyBand, Signature, STANDARD_SLOTS } from "../_shared";
import type { TemplateDefinition, TemplateInput } from "../../engine/types";

const T = { orbitEnd: 150, pushStart: 160, pushEnd: 238, headline: 60, copyLeave: 236, endCard: 256 };

/**
 * The laptop is already open. The camera walks a third of the way around
 * it - from behind the hinge on one side to in front on the other - then
 * commits, pushing into the screen until it nearly fills the frame.
 */
const Component: React.FC<TemplateInput> = ({ screens, logo, brand, copy, cta }) => {
  const frame = useCurrentFrame();
  const { width, height, fps } = useVideoConfig();
  const L = layoutFor(width, height);
  const t = frame / fps;
  const wide = L.aspect === "16:9";

  const laptopWidth = Math.min(L.device.width * (wide ? 0.72 : 0.74), L.device.height * (wide ? 1.02 : 0.9));
  const g = macbookGeometry(laptopWidth);
  const hingeX = L.device.x + L.device.width / 2 - width / 2;
  const hingeY = L.device.y + L.device.height * (wide ? 0.72 : L.aspect === "1:1" ? 0.74 : 0.64) - height / 2;

  const brightness = kf(frame, [{ at: 4, value: 0 }, { at: 26, value: 1, easing: ease.cinematicOut }]);
  const push = wide ? 1.6 : 1.22;

  const move = cameraAt(frame, [
    { at: 0, dolly: 0.88, orbitX: 20, orbitY: -46, roll: -2.5, x: -hingeX * 0.5 },
    { at: T.orbitEnd, dolly: 1, orbitX: 11, orbitY: 9, roll: 0, x: 0, easing: ease.cinematicInOut },
    { at: T.pushStart, dolly: 1 },
    { at: T.pushEnd, dolly: push, orbitX: 5, orbitY: 1.5, easing: ease.cinematicInOut },
    { at: T.endCard + 24, dolly: push * 0.94, orbitY: -4, easing: ease.smooth },
  ]);
  const camera = addCamera(move, {
    orbitY: drift(t, DRIFT_PERIODS.slow, 0.5),
    y: drift(t, DRIFT_PERIODS.fast, L.unit * 0.002, 2),
  });

  const exposure = ease.cinematicOut(progress(frame, 0, 22));
  const endDim = ease.cinematicIn(progress(frame, T.endCard, T.endCard + 20));

  return (
    <AbsoluteFill style={{ backgroundColor: "#000" }}>
      <Environment primary={brand.primary} accent={brand.accent} exposure={exposure * (1 - endDim * 0.6)} keyLight={{ x: 0.62, y: 0.12 }} dust />
      <Stage camera={camera} origin={{ x: 0.5, y: 0.45 }}>
        <Placed x={hingeX} y={hingeY} width={0} height={0}>
          <Surface y={g.deckThickness + 3} size={L.unit * 14} color={brand.primary} focus={0.48} opacity={exposure} />
          <ContactShadow width={g.width} depth={g.deckDepth} y={g.deckThickness + 2} z={g.deckDepth / 2} strength={0.8} softness={30} />
          <ScreenSpill width={g.width} depth={g.deckDepth} y={g.deckThickness + 2} z={g.deckDepth * 0.9} color={rgba(brand.accent, 0.5)} intensity={brightness * 0.7} />
          <MacBook
            width={laptopWidth}
            lidAngle={LID_OPEN}
            brightness={brightness}
            accent={brand.accent}
            screen={(dims) => (
              <ScreenSequence screens={screens} width={dims.width} height={dims.height} from={10} to={T.endCard + 10} hold={Math.round(fps * 2.1)} transition="slide-left" transitionFrames={14} scrollAmount={0.8} driftZoom={1.02} dim={endDim * 0.7} />
            )}
          />
        </Placed>
      </Stage>
      <CopyBand layout={L} copy={copy} brand={brand} from={T.headline} leave={T.copyLeave} />
      <Signature layout={L} logo={logo} from={30} leave={T.endCard} />
      <EndCard from={T.endCard} cta={cta} brand={brand} logo={logo} />
    </AbsoluteFill>
  );
};

export const template: TemplateDefinition = {
  id: "macbook-orbit",
  name: "MacBook — Orbit & Zoom",
  tagline: "The camera walks a third of the way around an open laptop, then commits to the screen.",
  category: "laptop",
  devices: ["macbook"],
  durationInFrames: 300,
  aspects: ["16:9", "1:1", "9:16"],
  slots: STANDARD_SLOTS,
  component: Component,
};
